CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDENTS(
    STUDENT_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    TEAM_ID INTEGER,
    STUDENT_PROGRAM VARCHAR(255) NOT NULL,
    COURSE_SECTION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
    TEAM_ID SERIAL PRIMARY KEY,
    TEAM_NAME VARCHAR(255) NOT NULL,
    LIAISON INTEGER
);

CREATE TABLE IF NOT EXISTS TEAM_MEMBERS(
    TEAM_ID INTEGER,
    STUDENT_ID INTEGER
);

ALTER TABLE IF EXISTS STUDENTS ADD FOREIGN KEY (USER_ID) REFERENCES USERS;

ALTER TABLE IF EXISTS STUDENTS ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAMS;

ALTER TABLE IF EXISTS TEAMS ADD FOREIGN KEY (LIAISON) REFERENCES STUDENTS;

ALTER TABLE IF EXISTS TEAM_MEMBERS ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS;

ALTER TABLE IF EXISTS TEAM_MEMBERS ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAMS;
