CREATE TABLE IF NOT EXISTS USERS(
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    PRIMARY KEY (USERNAME, PASSWORD),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID uuid PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRICE MONEY,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);